### ISSUE TITLE
DigitalOcean Spaces Installation (+ Problem with installation)

### ISSUE THREAD

**Issue by mciszczon** [laosb/ghos3#16]
Hi there! Thanks for forking the original adapter and maintaining it.

I have a Ghost blog on DigitalOcean and wanted to connect it with its Spaces for storage. After some tinkering I finally adapted the installation instructions and wanted to share it for anyone (myself included) in the future. If you're interested in adding it to the README file, I can make a quick PR for that.

Here's what worked for me:

```json
{
  "storage": {
    "active": "s3",
    "media": {
      "adapter": "s3"
    },
    "files": {
      "adapter": "s3"
    },
    "s3": {
      "accessKeyId": "...",
      "secretAccessKey": "...",
      "region": "<REGION_NAME like fra1>",
      "bucket": "<BUCKET_NAME>",
      "assetHost": "<CDN_ENDPOINT>",
      "pathPrefix": "<ANYTHING_YOU_LIKE>",
      "endpoint": "https://<REGION>.digitaloceanspaces.com"
    }
  }
}
```

Not sure if the `region` param is required though, so I added it for the sake of explicitness. One tricky part is that the `endpoint` param has to have the bucket name omited, as it is added automatically from the `bucket` param. I did not check if it would work by adding the bucket name straight into the `endpoint` URL and just removing the `bucket` param from the config.

Also, when I tried to install the adapter into the `/content/adapters/storage/s3` as instructed, it wouldn't get picked up by Ghost on startup. It worked, hovewer, when I installed it into `/current/core/server/adapters/storage/s3`—not sure why.

Node: `v18.19.0`
Ghost-CLI: `1.25.3`
Ghost: `5.76.0 (at /var/www/ghost)`

**Comment by laosb** [comment]
`region` is only supposed to be present when using AWS endpoint I think.

> Also, when I tried to install the adapter into the /content/adapters/storage/s3 as instructed, it wouldn't get picked up by Ghost on startup. It worked, hovewer, when I installed it into /current/core/server/adapters/storage/s3—not sure why.

I don't recognize `/current/core/server/` part of the path though. Where did you get the idea of this?

**Comment by mciszczon** [comment]
> I don't recognize `/current/core/server/` part of the path though. Where did you get the idea of this?

`current` is just a symlink to the currently installed version of Ghost.

**Comment by pablorsk** [comment]
I'm working with DO, and this is my config file:

```yaml
  storage__active: s3

  # DO_SPACES_KEY
  storage__s3__accessKeyId: 'EX2PLYR______EQRX5GK'

  # DO_SPACES_SECRET
  storage__s3__secretAccessKey: 'B0t3EuSXlzwe________TyZCExorOUppN3Ks8JI'

  # DO_SPACES_REGION
  storage__s3__region: 'sfo3'

  # DO_SPACES_BUCKET
  storage__s3__bucket: 'our_bucket_name'

  # DO_SPACES_ENDPOINT: 'https://sfo3.digitaloceanspaces.com'
  storage__s3__endpoint: 'https://sfo3.digitaloceanspaces.com'

  storage__s3__forcePathStyle: 'true'
  storage__s3__pathPrefix: 'some-foler/saldoar/blog'
  storage__s3__assetHost: 'https://cdn.reyesoft.com/saldoar'
```
